module = "icon"

[icons]
trash  = "trash-2"
ellipsis_v = "ellipsis-vertical"
circle_alert = "circle-alert"
circle_dashed = "circle-dashed"
circle = "circle"
chevron_r = "chevron-right"
check = "check"
